title: Eduard-o
email: your-email@example.com
description: >-
  My thoughts, current projects, and future projects!
baseurl: ""
url: "https://Eduard-o.github.io"
github_username: Eduard-o
google_analytics:

# Build settings
theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
